# Learn more about configuring your app:
# https://shopify.dev/docs/apps/tools/cli/configuration

name = "TaxoAI"
client_id = ""
application_url = "https://localhost"

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[auth]
redirect_urls = [
  "https://localhost/auth/callback",
  "https://localhost/auth/shopify/callback",
  "https://localhost/api/auth/callback",
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = ["products/update"]
  uri = "/webhooks"

[access_scopes]
scopes = "read_products,write_products"

[pos]
embedded = false
